### ISSUE TITLE
Declaração de Posição do Produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-Est-dio-de-Beleza-Keuany#1]
- [x] O Estúdio de Beleza Keuany | É uma aplicação web no ramo da tecnologia que promove serviços online. _**É isso mesmo? O Estúdio é uma aplicação? Aqui, deveria ser o nome do produto**_

**Comment by gusrberto** [comment]
Alterado o tópico de Declaração de Posição do Produto para o nome da aplicação (BrowStyle).
