### ISSUE TITLE
Escopo do produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-Est-dio-de-Beleza-Keuany#2]
O escopo do produto me parece muito pequeno para ser tratado no contexto da disciplina.
Pelo que eu entendi refere-se a agendamento e disponibilização de portifólio (imagens). Se for apenas isso, a equipe irá precisar ampliar esse escopo.
Lembrando, uma coisa é o MVP (escopo da entrega) outra é o escopo necessário a ser trabalhado na disciplina.

**Comment by Raphides** [comment]
O escopo do projeto ainda não havia sido efetivamente descrito no documento, entretanto já decidimos o que faremos.

Olhando através de cada objetivo, faremos as seguintes funcionalidades:

### Diminuir o número de cancelamentos tardios
- **Notificação** lembrando da sessão marcada. Pensamos em mandar por Whatsapp/Telegram e/ou e-mail automaticamente.

### Garantir disponibilidade da vaga perdida em tempo hábil de inscrição.
- **Pedido de confirmação**. Funciona como uma notificação, mas se o cliente não responder ou responder que não vai, a sessão é cancelada.
- **Agenda virtual** que mostra os horários vagos e cheios. Uma vaga cancelada aparecia vaga na agenda imediatamente.
- **Sistema de Fila** que permite aos usuários entrarem na fila de um horário específico. A atualização do status dessa vaga seria notificado por e-mail ou WhatsApp/Telegram tbm.

### Alavancar o negócio
- **Informação geral da empresa**, como fotos, localização, funcionários que fazem as sessões, redes sociais, contato, tudo no website, complementando o Instagram e o WhatsApp.
- **Sistema de avaliação do serviço**. A Keu (nossa stakeholder) tinha seu negócio em outra cidade antes. Ela era bem conhecida por lá, mas vindo pra Brasília, ela perdeu essa base de clientes. O sistema de avaliação funcionaria como uma forma de tentar aproveitar essa base anterior de clientes que ela tinha.
