### ISSUE TITLE
Organização do Projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-Est-dio-de-Beleza-Keuany#3]
- [x] Inserir o Líder Estelar, para realização de feedbacks constantes para a equipe, assim como avaliar a qualidade das entregas.

- [x] faltam algumas responsabilidades a serem distribuídas, como: garantir a qualidade dos requisitos (ver e val de requisitos), representação de requisitos, declaração de requisitos, análise e negociação de requisitos

**Comment by Raphides** [comment]
Os papéis foram adicionados.
