### ISSUE TITLE
Etapas do processo de ER

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-Est-dio-de-Beleza-Keuany#4]
- [x] Em que momentos do processo de ER, as atividades serão executadas? planning, review, retro, etc? Insiram essa informação.

**Comment by gusrberto** [comment]
Foram definidos em que momento do ciclo de vida cada um dos processos de ER (Elicitação e Descoberta, Análise e Consenso, Descoberta...) serão aplicados.
